### PR TITLE
feature: add new account info standard support

### PR DESCRIPTION
**Pull request by ost-ptk**
_**Make sure to fill in all the below sections.**_

## Description

- removed old implementation of account info standard support (home and account list pages)
- added AIS name on the account details page as an additional data row

## Linked tickets

#628 

## Checklist

- [x] Make sure this PR title follows semantic release conventions: <https://semantic-release.gitbook.io/semantic-release/#commit-message-format>

- [ ] If the PR adds any new text to the UI, make sure they are localized

- [ ] Include a screenshot or recording if implementing significant UI or user flow change

- [x] When this PR affects architecture changes wait for review from Piotr before merging

### CODE REVIEW

**Comment by piotrwitek** [comment]
@ost-ptk could you please check if the connected sites list view is using a custom name? because I couldn't notice any related changes in the PR and wasn't sure about it.

**Review by piotrwitek — APPROVED** [review]
Looks good @ost-ptk

**Comment by ost-ptk** [comment]
> @ost-ptk could you please check if the connected sites list view is using a custom name? because I couldn't notice any related changes in the PR and wasn't sure about it.

Yes, we didn't change there anything

**Comment by piotrwitek** [comment]
Ok then looks good to merge thanks :)

**Pull request merged**
